apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: front-app
  labels:
    app: front-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
        - name: front-app
          image: "1karinav/front-app:{{ .Values.imageTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config
          configMap:
            name: front-app-cm