swagger: "2.0"
produces:
  - application/json
host: "localhost:8080"
basePath: /service-flight
definitions:
  CreateFlightIn:
    properties:
      arrival:
        format: date-time
        type: string
      departure:
        format: date-time
        type: string
      from:
        type: string
      id:
        type: string
      to:
        type: string
    required:
      - id
      - from
      - to
      - departure
      - arrival
    type: object
  CreateFlightOut:
    type: object
  DeleteFlightIn:
    properties:
      id:
        type: string
    required:
      - id
    type: object
  DeleteFlightOut:
    type: object
  ListFlightsIn:
    properties:
      from:
        type: string
      to:
        type: string
    type: object
  ListFlightsOut:
    properties:
      arrival:
        format: date-time
        type: string
      departure:
        format: date-time
        type: string
      from:
        type: string
      id:
        type: string
      to:
        type: string
    required:
      - id
      - from
      - to
      - departure
      - arrival
    type: object
  UpdateFlightIn:
    properties:
      arrival:
        format: date-time
        type: string
      departure:
        format: date-time
        type: string
      from:
        type: string
      id:
        type: string
      to:
        type: string
    required:
      - id
    type: object
  UpdateFlightOut:
    type: object
info:
  title: Airport board
  version: some-version
paths:
  /createFlight/:
    post:
      description: создать новый рейс
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/CreateFlightIn'
      responses:
        "200":
          description: Successful
          schema:
            properties:
              result:
                $ref: '#/definitions/CreateFlightOut'
            required:
              - result
            type: object
        default:
          description: All error cases
          schema:
            properties:
              error:
                properties:
                  kind:
                    enum:
                      - validation
                      - server
                    type: string
                  message:
                    type: string
                required:
                  - kind
                  - message
                type: object
            required:
              - error
            type: object
  /deleteFlight/:
    delete:
      description: удалить рейс
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/DeleteFlightIn'
      responses:
        "200":
          description: Successful
          schema:
            properties:
              result:
                $ref: '#/definitions/DeleteFlightOut'
            required:
              - result
            type: object
        default:
          description: All error cases
          schema:
            properties:
              error:
                properties:
                  kind:
                    enum:
                      - validation
                      - server
                    type: string
                  message:
                    type: string
                required:
                  - kind
                  - message
                type: object
            required:
              - error
            type: object
  /listFlights/:
    get:
      description: получить расписание рейс
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ListFlightsIn'
      responses:
        "200":
          description: Successful
          schema:
            properties:
              result:
                $ref: '#/definitions/ListFlightsOut'
            required:
              - result
            type: object
        default:
          description: All error cases
          schema:
            properties:
              error:
                properties:
                  kind:
                    enum:
                      - validation
                      - server
                    type: string
                  message:
                    type: string
                required:
                  - kind
                  - message
                type: object
            required:
              - error
            type: object
  /updateFlight/:
    patch:
      description: обновить информацию о рейсе
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UpdateFlightIn'
      responses:
        "200":
          description: Successful
          schema:
            properties:
              result:
                $ref: '#/definitions/UpdateFlightOut'
            required:
              - result
            type: object
        default:
          description: All error cases
          schema:
            properties:
              error:
                properties:
                  kind:
                    enum:
                      - validation
                      - server
                    type: string
                  message:
                    type: string
                required:
                  - kind
                  - message
                type: object
            required:
              - error
            type: object
