on:
  push:
    tags:
      - 'v*.*'

jobs:
  build-and-push-backend:
    name: build backend for release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Kaniko build
      - uses: aevea/action-kaniko@master
        with:
          image: 1karinav/avia-back
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_file: Dockerfile
          path: backend
          tag: ${{ github.ref_name }}

  build-and-push-frontend:
    name: build frontend for release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Kaniko build
      - uses: aevea/action-kaniko@master
        with:
          image: 1karinav/front-app
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_file: Dockerfile
          path: frontend
          tag: ${{ github.ref_name }}